// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"MaterialBase","status":true,"description":"素材をデータベースとして登録、参照できます。","parameters":{"ImageList":"[]","AudioList":"[]"}},
{"name":"PixiApngAndGif","status":true,"description":"","parameters":{}},
{"name":"ApngPicture","status":true,"description":"APNGピクチャプラグイン","parameters":{"PictureList":"[]","EnemyList":"[]","SideEnemyList":"[]","SceneApngList":"[]","DefaultLoopTimes":"0","StopLastFrame":"false","AllStopSwitch":"0","FrameCount":"0","NoSmooth":"false"}},
{"name":"NRP_ChangeCharacterSpeed","status":true,"description":"v1.01 キャラクターの移動速度を細かく変更します。","parameters":{"DefaultAlwaysDash":"","PlayerSpeed":"","PlusSpeedDash":"0.001","<BasicSpeedRate>":"","PlayerBasicSpeedRate":"150","EventBasicSpeedRate":"100","<Vehicles>":"","BoatSpeed":"","ShipSpeed":"","AirShipSpeed":""}},
{"name":"Mihil_NamedGameVariables","status":true,"description":"ゲーム内変数を名前で呼べるように","parameters":{}},
{"name":"ReliveTools","status":true,"description":"Relive Live開発用の便利ツール","parameters":{}},
{"name":"CharacterGraphicExtend","status":true,"description":"キャラクターグラフィック表示拡張プラグイン","parameters":{"EventHideInvalid":"false"}},
{"name":"TitleImageChange","status":true,"description":"タイトル画面変更プラグイン","parameters":{"StoryPhaseVariable":"5","PriorityVariable":"0","TitleList":"[\"{\\\"StoryPhaseCondition\\\":\\\"0\\\",\\\"TitleImage\\\":\\\"Relive_Title3\\\",\\\"TitleBgm\\\":\\\"In That Mood\\\"}\",\"{\\\"StoryPhaseCondition\\\":\\\"1\\\",\\\"TitleImage\\\":\\\"Relive_Title3\\\",\\\"TitleBgm\\\":\\\"In That Mood\\\"}\"]"}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"AlwaysDash":"false","CommandRemember":"false","TouchUi":"false","BgmVolume":"100","BgsVolume":"100","MeVolume":"100","SeVolume":"100","EraseAlwaysDash":"true","EraseCommandRemember":"false","EraseTouchUi":"true","EraseBgmVolume":"false","EraseBgsVolume":"false","EraseMeVolume":"false","EraseSeVolume":"false"}},
{"name":"MOG_TitleCommands","status":true,"description":"(v1.3) タイトルメニューのコマンドを画像で表示します","parameters":{"-> Main <<<<<<<<<<<<<<<<<<<<<<<":"","Animation Mode":"0","Left & Right Input":"false","Shake Duration":"30","Slide X-Axis":"-100","Slide Y-Axis":"0","-> Cursor <<<<<<<<<<<<<<<<<<<<<<<":"","Cursor X-Axis":"0","Cursor Y-Axis":"5","Cursor Visible":"true","Cursor Wave Animation":"true","Cursor Rotation Animation":"false","Cursor Rotation Speed":"0.05","-> Commands <<<<<<<<<<<<<<<<<<<<<<<":"","Command Pos 1":"700,200","Command Pos 2":"700,250","Command Pos 3":"700, 300","Command Pos 4":"690,440","Command Pos 5":"345,498","Command Pos 6":"345,530","Command Pos 7":"0,192","Command Pos 8":"0,224","Command Pos 9":"0,256","Command Pos 10":"0,288"}}
];
