// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"MaterialBase","status":true,"description":"素材をデータベースとして登録、参照できます。","parameters":{"ImageList":"[]","AudioList":"[]"}},
{"name":"PixiApngAndGif","status":true,"description":"","parameters":{}},
{"name":"ApngPicture","status":true,"description":"APNGピクチャプラグイン","parameters":{"PictureList":"[]","EnemyList":"[]","SideEnemyList":"[]","SceneApngList":"[]","DefaultLoopTimes":"0","StopLastFrame":"false","AllStopSwitch":"0","FrameCount":"0","NoSmooth":"false"}},
{"name":"NRP_ChangeCharacterSpeed","status":true,"description":"v1.01 キャラクターの移動速度を細かく変更します。","parameters":{"DefaultAlwaysDash":"","PlayerSpeed":"","PlusSpeedDash":"0.001","<BasicSpeedRate>":"","PlayerBasicSpeedRate":"150","EventBasicSpeedRate":"100","<Vehicles>":"","BoatSpeed":"","ShipSpeed":"","AirShipSpeed":""}},
{"name":"Mihil_NamedGameVariables","status":true,"description":"ゲーム内変数を名前で呼べるように","parameters":{}},
{"name":"ReliveTools","status":true,"description":"Relive Live開発用の便利ツール","parameters":{}},
{"name":"CharacterGraphicExtend","status":true,"description":"キャラクターグラフィック表示拡張プラグイン","parameters":{"EventHideInvalid":"false"}},
{"name":"TitleImageChange","status":true,"description":"タイトル画面変更プラグイン","parameters":{"StoryPhaseVariable":"5","PriorityVariable":"0","TitleList":"[\"{\\\"StoryPhaseCondition\\\":\\\"0\\\",\\\"TitleImage\\\":\\\"Relive_Title3\\\",\\\"TitleBgm\\\":\\\"In That Mood\\\"}\",\"{\\\"StoryPhaseCondition\\\":\\\"1\\\",\\\"TitleImage\\\":\\\"Relive_Title3\\\",\\\"TitleBgm\\\":\\\"In That Mood\\\"}\"]"}},
{"name":"CustomizeConfigDefault","status":true,"description":"オプションデフォルト値設定プラグイン","parameters":{"AlwaysDash":"false","CommandRemember":"false","TouchUi":"false","BgmVolume":"100","BgsVolume":"100","MeVolume":"100","SeVolume":"100","EraseAlwaysDash":"true","EraseCommandRemember":"false","EraseTouchUi":"true","EraseBgmVolume":"false","EraseBgsVolume":"false","EraseMeVolume":"false","EraseSeVolume":"false"}},
{"name":"MOG_TitleCommands","status":true,"description":"(v1.3) タイトルメニューのコマンドを画像で表示します","parameters":{"-> Main <<<<<<<<<<<<<<<<<<<<<<<":"","Animation Mode":"0","Left & Right Input":"false","Shake Duration":"30","Slide X-Axis":"-100","Slide Y-Axis":"0","-> Cursor <<<<<<<<<<<<<<<<<<<<<<<":"","Cursor X-Axis":"0","Cursor Y-Axis":"5","Cursor Visible":"true","Cursor Wave Animation":"true","Cursor Rotation Animation":"false","Cursor Rotation Speed":"0.05","-> Commands <<<<<<<<<<<<<<<<<<<<<<<":"","Command Pos 1":"700,200","Command Pos 2":"700,250","Command Pos 3":"700, 300","Command Pos 4":"690,440","Command Pos 5":"345,498","Command Pos 6":"345,530","Command Pos 7":"0,192","Command Pos 8":"0,224","Command Pos 9":"0,256","Command Pos 10":"0,288"}},
{"name":"DevToolsManage","status":true,"description":"開発支援プラグイン","parameters":{"StartupDevTool":"true","ShortcutList":"","ShowFPS":"OFF","CutTitle":"0","RapidStart":"false","RapidSpeed":"2","SlowSpeed":"2","InvalidMessageSkip":"false","MenuBarVisible":"true","ClickMenu":"1","OutputStartupInfo":"true","StartupOnTop":"false","UseReloadData":"true"}},
{"name":"HalfMove","status":false,"description":"半歩移動プラグイン","parameters":{"8方向移動":"true","8方向移動スイッチ":"0","イベントすり抜け":"true","強制中無効":"false","角回避":"true","斜め移動中減速":"false","トリガー拡大":"false","実歩数調整":"false","上半分移動不可地形":"[\"0\"]","上半分移動不可Region":"[\"0\"]","下半分移動不可地形":"[\"0\"]","下半分移動不可Region":"[\"0\"]","右半分移動不可地形":"[\"0\"]","右半分移動不可Region":"[\"0\"]","左半分移動不可地形":"[\"0\"]","左半分移動不可Region":"[\"0\"]","右上移動不可地形":"[\"0\"]","右上移動不可Region":"[\"0\"]","右下移動不可地形":"[\"0\"]","右下移動不可Region":"[\"0\"]","左上移動不可地形":"[\"0\"]","左上移動不可Region":"[\"0\"]","左下移動不可地形":"[\"0\"]","左下移動不可Region":"[\"0\"]","全方向移動不可地形":"[\"0\"]","全方向移動不可Region":"[\"0\"]","イベント複数起動防止":"false","イベント位置重複OK":"false"}},
{"name":"CustomizeErrorScreen","status":true,"description":"エラー画面表示改善プラグイン","parameters":{"MainMessage":"エラーが発生しました。エラー内容を添えて以下にお問い合わせください。","HyperLink":"","OutputDetail":"true"}},
{"name":"JumpSpeedCustomize","status":true,"description":"ジャンプ速度調整プラグイン","parameters":{}},
{"name":"WindowBlinkStop","status":true,"description":"ウィンドウ点滅停止プラグイン","parameters":{}},
{"name":"AlwaysGameActive","status":true,"description":"常時ゲームアクティブプラグイン","parameters":{}},
{"name":"PauseSignToTextEnd","status":true,"description":"ポーズサインの末尾表示プラグイン","parameters":{"validateSwitchId":"0","invisibleSwitchId":"0"}},
{"name":"MouseInvalidate","status":true,"description":"タッチ操作無効化プラグイン","parameters":{}},
{"name":"CheckFreezeStrict","status":true,"description":"厳格フリーズチェックプラグイン","parameters":{"freezeCommandCount":"100000"}},
{"name":"MousePointerErase","status":true,"description":"マウスポインタ消去プラグイン","parameters":{}},
{"name":"EventDebugger","status":true,"description":"イベントデバッグプラグイン","parameters":{"stepStart":"F7","stepIn":"F11","stepOver":"F10","continue":"F6","toggleWindow":"none","watchVariable":"F1","maxWatchNum":"3","eventTest":"true","suppressFunc":"false","okHandler":"F11","cancelHandler":"F6","simultaneousCtrl":"false","simultaneousAlt":"false","scriptDebug":"0","disableDebugCtrlKey":"true","showDevTools":"true","breakSwitchId":"0"}}
];
