// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"PluginCommonBase","status":true,"description":"パラメータ解析を提供する共通基盤です","parameters":{}},
{"name":"MaterialBase","status":true,"description":"素材をデータベースとして登録、参照できます。","parameters":{"ImageList":"[]","AudioList":"[]"}},
{"name":"PixiApngAndGif","status":true,"description":"","parameters":{}},
{"name":"ApngPicture","status":true,"description":"APNGピクチャプラグイン","parameters":{"PictureList":"[]","EnemyList":"[]","SideEnemyList":"[]","SceneApngList":"[]","DefaultLoopTimes":"0","StopLastFrame":"false","AllStopSwitch":"0","FrameCount":"0","NoSmooth":"false"}},
{"name":"NRP_ChangeCharacterSpeed","status":true,"description":"v1.01 キャラクターの移動速度を細かく変更します。","parameters":{"DefaultAlwaysDash":"","PlayerSpeed":"","PlusSpeedDash":"0.001","<BasicSpeedRate>":"","PlayerBasicSpeedRate":"150","EventBasicSpeedRate":"100","<Vehicles>":"","BoatSpeed":"","ShipSpeed":"","AirShipSpeed":""}},
{"name":"Mihil_NamedGameVariables","status":true,"description":"ゲーム内変数を名前で呼べるように","parameters":{}},
{"name":"ReliveTools","status":true,"description":"Relive Live開発用の便利ツール","parameters":{}},
{"name":"CharacterGraphicExtend","status":true,"description":"キャラクターグラフィック表示拡張プラグイン","parameters":{"EventHideInvalid":"false"}}
];
